name = "LMoP 3.1.1: Old Owl Well"
location = "Old Owl Well"

notes = """
A necromancer, oh no!
"""

[groups.evil_mage]
monster = "evil_mage"
name = "Mr_Necromancer"
alias = "Mr. Necromancer"
count = 1
