name = "LMoP 1.1.1: Goblin Ambush"
location = "Triboar Trail"

notes = """
Four goblins are hlding in the woods, two on each side of the road. They wait
until someone approaches the bodies and then attack.

When the time comes for the goblins to act, two of them rush forward and make
melee attacks while two goblins stand 30 feet away from the party and make
ranged attacks.

When three goblins are defeated, the last goblin attempts to flee, heading for
the goblin trail.
"""

[groups.goblins]
monster = "goblin"
count = 4
max_hp = [6, 5, 7, 4]
