dist: xenial
sudo: required
language: python
python:
- '3.6'
- '3.7'
install: pip install tox-travis
script: tox
notifications:
  slack:
    rooms:
      secure: gWW6WrhKw+vRrqx/StxxLhw+LFkW77l/QC5Zr1GZR/rYtdu1o3mRRSufU60te2hNyh6lsCNJBVfuyy1HWR0viDQSa54GNdEgs39mEZRnUDjVmyrYDR0yP4YbyOH89eg94vwAXCb2xb4DyKzdSoJsMwS1htneJWdlckwio0AxBFNCpRqokcKScatOOeO9wt38bI5DAePEBrKUKJAG4fagyvOAWfNpoeSu6XYEj7zo+la3LhEYuemPGN7QsA78/CaVUsimxnr8bqFKntViBELTpjvWQwZ3vKpMboh9yAq7GlWJ2KG9+xoTZX6Rh/dxwtWLgK1bAKZ4414ofSiPtP7VGIaZNLa8nrXP6FLxtKegZrMmlhydK/dkAaskVf7j83Srrp1A31Dpc99b353HdpJFIwRXBgGq+pcenAwqFyDjqdF1lKi+lmnxUtseoPBQS0+cn+EtgaaPhLtyyX1vBNgmRGrqKV2PILAW0jOhcBO2AAE08o5jdrb5AXD6pOjeFsqQZ4ovwMkBfd6YOpUUC9m10cDWTTkSY++dNAwzOIlLhrkif0mM3iPMEiIUYt9LuLdhBL+Ro9HWYLUgqh2pVOtnhF1w1949nNzHJQXTDNuu5fbJVgxuICPpbwEErpPa9DQQQdWG9DXoNu/Akb2OsX3PTB5BlFS12/R9jSOnG7s44zw=
    on_success: always
    on_failure: always
    template:
    - Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>)
      for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`.
    - 'Execution time: *%{duration}*'
    - 'Message: %{message}'
