name = "evil_mage"
size = "medium"
mtype = "humanoid:human"
race = "human"
alignment = "lawful evil"
ac = 12
armor = ""
max_hp = "5d8"
xp = 200
str = 9
dex = 14
con = 11
int = 17
wis = 12
cha = 11
vulnerable = ""
resist = ""
immune = ""
languages = "Common, Draconic, Dwarvish, Elvish"
cr = 1
speed = 30
notes = """
Evil mages hunger for arcane power and dwell in isolated places, where
they can perform terrible magical experiments without interference.
"""

[skills]
stealth = 6

[senses]
darkvision = 0
perception = 11

[features.spellcasting]
name = "Spellcasting"
description = """
The mage is a 4th·level spellcaster that uses Intelligence as its
spellcasting ability (spell save DC 13; +5 to hit with spell attacks).
"""
cantrips = ["Light", "Mage Hand", "Shocking Grasp"]
spells = [
    ["Charm Person", "Magic Missile"],
    ["Hold Person", "Misty Step"]
]
slots = [4, 3]
slots_used = [0, 0]

[actions.quarterstaff]
name = "Quarterstaff"
description = """
Melee Weapon Attack: +1 to hit, reach 5 ft., one target.
Hit: 3 (ld8 - 1) bludgeoning damage.
"""
