name = "goblin"
size = "small"
mtype = "humanoid:goblinoid"
race = "goblin"
alignment = "neutral evil"
ac = 15
armor = "leather armor, shield"
max_hp = "2d6"
speed = 30
str = 8
dex = 14
con = 10
int = 10
wis = 8
cha = 8
vulnerable = ""
resist = ""
immune = ""
languages = "Common, Goblin"
cr = 0.25
xp = 50
notes = """
Goblins are black-hearted, gather in overwhelming numbers, and crave power,
which they abuse.
"""

[skills]
stealth = 6

[senses]
darkvision = 60
perception = 9

[features.nimbleescape]
name = "Nimble Escape"
description = """
The goblin can take the Disengage or Hide action as a bonus action on each
of its turns.
"""

[actions.scimitar]
name = "Scimitar"
description = """
Melee Weapon Attack: +4 to hit, reach 5 ft., one target.
Hit: 5 (ld6 + 2) slashing damage.
"""

[actions.shortbow]
name = "Short Bow"
description = """
Ranged Weapon Attack: +4 to hit, range 80 ft./320 ft., one target.
Hit: 5 (1d6 + 2) piercing damage.
"""
