name = "young_green_dragon"
size = "large"
mtype = "dragon"
race = "dragon"
alignment = "lawful evil"
ac = 18
armor = "natural armor"
max_hp = "16d10+48"
speed = "land: 40, fly: 60, swim: 40"
str = 19
dex = 12
con = 17
int = 16
wis = 13
cha = 15
vulnerable = ""
resist = ""
immune = "poison, poisoned"
languages = "Common, Draconic"
cr = 8
xp = 3900
notes = """
Thoroughly evil, green dragons delight in subverting and corrupting the
good-hearted. They prefer to dwell in ancient forests.
"""

[skills]
deception = 5
stealth = 4
dex_save = 4
con_save = 6
wis_save = 4
cha_save = 5

[senses]
darkvision = 120
blindsight = 30
perception = 17

[features.amphibious]
name = "Amphibious"
description = "The dragon can breathe air and water."

[actions.multiattack]
name = "Multiattack"
description = """
The dragon makes three attacks, one with its bite and two with its claws.
"""

[actions.bite]
name = "Bite"
description = """
Melee Weapon Attack: +7 to hit, reach 10 ft., one target.
Hit: 15 (2dl0 + 4) piercing damage plus 7 (2d6) poison damage.
"""

[actions.claw]
name = "Claw"
description = """
Melee Weapon Attack: +7 to hit, reach 5 ft., one target.
Hit: 11 (2d6 + 4) slashing damage.
"""

[actions.breath]
name = "Poison Breath (Recharge 5-6)"
description = """
The dragon breathes poisonous gas in a 30-foot cone. Each creature in the
cone must make a DC 16 Constitution saving throw, taking 42 (12d6) poison
damage on a failed save, or half as much damage on a successful one.
"""
